### PR TITLE
Fixing notices and handling socket error 35.

### PR DESCRIPTION
**Pull request by jpirkey**
- Fixing method signature for `Worker->askForWork` to allow optional `$monitor` and `$lastJobTime` 
- Adding support for ignoring socket error 35 in Client connection.
- Fixing error message to use the correct var in `Connection->close`.

### CODE REVIEW

**Comment by jpirkey** [comment]
@brianlmoon what was `$et` supposed to represent at https://github.com/brianlmoon/net_gearman/blob/timeout_close_refactor/Net/Gearman/Connection.php#L391

is that supposed to be `$timeout` instead?

**Comment by rokclimb15** [comment]
@jpirkey that was the fix I applied which seems to be working as intended.

**Comment by jpirkey** [comment]
@rokclimb15 one of my starred items in google ... let me check that out.

**Comment by jpirkey** [comment]
@rokclimb15 i merged that pull request.  I'm going to update my downstream branch as well.

**Pull request merged**
